version: 2
jobs:
  build:
    working_directory: /book
    docker:
      - image: vvakame/review
    steps:
      - checkout
      - run: git submodule init && git submodule update

      # TODO cache npm modules
      - run: npm run global
      - run: npm install

      - run: npm run pdf
      - store_artifacts:
          path: /book/articles/revised2-typescript-in-definitelyland.pdf
          destination: PDF data

      - run: npm run epub
      - store_artifacts:
          path: /book/articles/revised2-typescript-in-definitelyland.epub
          destination: EPUB data

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
